baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My first Hugo site'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About me"
    url = "/about_me"
    weight = 3

[params]
  custom_css = ["custom.css"]
